name: CI # builds CV and triggers CI of personal webpage
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # schedule:
  #     - cron: "0 0 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        shell: bash
        run: |
          make
      #   uses: xu-cheng/latex-action@v3
      #   with:
      #     root_file: main.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow on b-fg.github.io
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'b-fg',
            repo: 'b-fg.github.io',
            workflow_id: 'jekyll.yml',
            ref: 'main'
          })
