name: CI # builds CV and triggers CI of personal webpage
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  schedule:
      - cron: "0 0 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Update Google Scholar stats
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install deps + run
        run: |
              python -m pip install --upgrade pip
              python -m venv /tmp/venv
              . /tmp/venv/bin/activate
              pip install requests bs4
              python get_scholar_data.py
      - name: Commit updated Google scholar data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f ".scholar_cache/scholar_data.json" ] && [ -f ".scholar_cache/scholar_data.tex" ]; then
            git add .scholar_cache/scholar_data.json .scholar_cache/scholar_data.tex
            git commit -m "Updated .scholar_data from CI" || echo "No changes to commit"
            git push
          else
            echo "No cache files found to commit."
          fi

      - name: Compile LaTeX document (after installing dependencies)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          pre_compile: |
            export SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }}
            apk --update add jq
          post_compile: make fetch=0

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Commit updated main.pdf and Google scholar data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f "main.pdf" ]; then
            git add main.pdf
            git commit -m "Updated main.pdf from CI" || echo "No changes to commit"
            git push
          else
            echo "No cache files found to commit."
          fi

  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow on b-fg.github.io
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'b-fg',
            repo: 'b-fg.github.io',
            workflow_id: 'jekyll.yml',
            ref: 'main'
          })
